# Generated by Django 3.1.7 on 2021-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(default='', max_length=200)),
                ('middle_Name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_Name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(default='00000', max_length=7, verbose_name='pin code')),
            ],
        ),
    ]
