# Generated by Django 3.1.7 on 2021-03-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_recruiter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='first_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='middle_Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
