# Generated by Django 3.1.7 on 2021-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_auto_20210304_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='middle_Name',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='first_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='last_Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
