# Generated by Django 3.1.7 on 2021-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_auto_20210305_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='Address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
