# Generated by Django 3.1.7 on 2021-03-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_auto_20210305_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
