# Generated by Django 3.1.7 on 2021-03-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0010_profile_state'),
        ('recruiter', '0008_auto_20210305_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='created_profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_profiles', to='job_profile.Profile'),
        ),
    ]
