# Generated by Django 3.1.7 on 2021-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_remove_recruiternotification_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='unseen_notification',
            field=models.IntegerField(default=0),
        ),
    ]
