# Generated by Django 3.1.7 on 2021-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_recruiter_unseen_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='password',
            field=models.CharField(default='samir', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='DOB',
            field=models.DateField(default='2020-02-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(default='sam', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(default='sam', max_length=200),
            preserve_default=False,
        ),
    ]
