# Generated by Django 3.1.7 on 2021-03-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_auto_20210308_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(default='s@s.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
