# Generated by Django 3.1.7 on 2021-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0015_recruiter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='intershala_authorize',
            field=models.BooleanField(default=False),
        ),
    ]
