# Generated by Django 3.1.7 on 2021-03-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_password'),
        ('recruiter', '0022_recruiterrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecruiterRating',
            new_name='RecruiterReview',
        ),
    ]
