# Generated by Django 3.1.7 on 2021-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0023_auto_20210312_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
    ]
