# Generated by Django 3.1.7 on 2021-03-14 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0024_recruiter_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 14, 7, 6, 24, 304373, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
