# Generated by Django 3.1.7 on 2021-03-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0025_recruiter_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
