# Generated by Django 3.1.7 on 2021-03-06 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0002_auto_20210306_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='intershalaemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 6, 11, 51, 5, 447034, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
