# Generated by Django 3.1.7 on 2021-03-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0005_auto_20210306_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intershalaemployee',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='intershalaemployee',
            old_name='last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='intershalaemployee',
            old_name='middle_Name',
            new_name='middle_name',
        ),
    ]
