# Generated by Django 3.1.7 on 2021-03-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_remove_recruiter_intershala_authorize'),
        ('intershala_admin', '0007_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='recruiter',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
            preserve_default=False,
        ),
    ]
