# Generated by Django 3.1.7 on 2021-03-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0008_adminnotification_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminnotification',
            old_name='active',
            new_name='seen',
        ),
    ]
