# Generated by Django 3.1.7 on 2021-03-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0009_auto_20210308_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intershala_admin.intershalaemployee')),
            ],
        ),
    ]
