# Generated by Django 3.1.7 on 2021-03-09 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intershala_admin', '0011_intershalaadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='intershalaadmin',
            name='user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
