# Generated by Django 3.1.7 on 2021-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0012_intershalaadmin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershalaadmin',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intershalaadmin',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intershalaemployee',
            name='middle_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
