# Generated by Django 3.1.7 on 2021-03-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_remove_recruiter_intershala_authorize'),
        ('intershala_admin', '0015_auto_20210310_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
    ]
