# Generated by Django 3.1.7 on 2021-03-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0016_auto_20210310_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershalaadmin',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
