# Generated by Django 3.1.7 on 2021-03-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0017_auto_20210310_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intershala_admin.intershalaadmin'),
        ),
    ]
