# Generated by Django 3.1.7 on 2021-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0018_adminnotification_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntershalaCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_description', models.TextField()),
                ('company_established', models.DateField()),
                ('website', models.EmailField(max_length=254)),
                ('rating', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
