# Generated by Django 3.1.7 on 2021-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_remove_recruiter_intershala_authorize'),
        ('intershala_admin', '0019_intershalacompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='intershalacompany',
            name='recruiter',
            field=models.ManyToManyField(to='recruiter.Recruiter'),
        ),
    ]
