# Generated by Django 3.1.7 on 2021-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_remove_recruiter_intershala_authorize'),
        ('intershala_admin', '0020_intershalacompany_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershalacompany',
            name='recruiter',
            field=models.ManyToManyField(null=True, to='recruiter.Recruiter'),
        ),
    ]
