# Generated by Django 3.1.7 on 2021-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0021_auto_20210311_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershalacompany',
            name='website',
            field=models.URLField(),
        ),
    ]
