# Generated by Django 3.1.7 on 2021-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_remove_recruiter_intershala_authorize'),
        ('intershala_admin', '0022_auto_20210311_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershalacompany',
            name='recruiter',
            field=models.ManyToManyField(blank=True, null=True, to='recruiter.Recruiter'),
        ),
    ]
