# Generated by Django 3.1.7 on 2021-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0023_auto_20210311_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershalacompany',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
