# Generated by Django 3.1.7 on 2021-03-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0024_auto_20210311_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intershala_admin.intershalacompany'),
        ),
    ]
