# Generated by Django 3.1.7 on 2021-03-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0027_auto_20210312_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershalaemployee',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='intershalaemployee',
            name='last_name',
            field=models.CharField(default='data', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intershalaemployee',
            name='middle_name',
            field=models.CharField(max_length=200),
        ),
    ]
