# Generated by Django 3.1.7 on 2021-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_notified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/qr_codes'),
        ),
    ]
