# Generated by Django 3.1.7 on 2021-03-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210322_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='get_notified',
        ),
    ]
