# Generated by Django 3.1.7 on 2021-03-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_profile', '0001_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='job_profile.Skill'),
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_questions', to='job_profile.profile'),
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
        migrations.AddField(
            model_name='assessment_answer',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profile.profile'),
        ),
        migrations.AddField(
            model_name='assessment_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profile.assessment_question'),
        ),
    ]
