# Generated by Django 3.1.7 on 2021-03-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('job_profile', '0002_auto_20210304_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
