# Generated by Django 3.1.7 on 2021-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0003_assessment_answer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=100),
        ),
    ]
