# Generated by Django 3.1.7 on 2021-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0004_auto_20210305_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(null=True, to='job_profile.Skill'),
        ),
    ]
