# Generated by Django 3.1.7 on 2021-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0005_auto_20210305_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='job_profile.Skill'),
        ),
    ]
