# Generated by Django 3.1.7 on 2021-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0006_auto_20210305_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='job_profile.Assessment_question'),
        ),
    ]
