# Generated by Django 3.1.7 on 2021-03-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0007_profile_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('In_Office', 'In_Office')], default='In_Office', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='immediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Delhi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_applicants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=models.CharField(choices=[('Full_Time', 'Full_time'), ('Part_Time', 'Part_time')], default='Full_Time', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='vacancy',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
