# Generated by Django 3.1.7 on 2021-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_applied_application'),
        ('job_profile', '0010_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='received_application',
            field=models.ManyToManyField(blank=True, null=True, related_name='received_applications', to='student.StudentApplication'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
