# Generated by Django 3.1.7 on 2021-03-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0011_auto_20210306_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intouch_applicants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rejected_applicants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_applicants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
