# Generated by Django 3.1.7 on 2021-03-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0012_auto_20210306_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number_of_applicants',
            new_name='applied_applicants',
        ),
    ]
