# Generated by Django 3.1.7 on 2021-03-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0026_auto_20210314_1922'),
        ('job_profile', '0015_auto_20210314_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
    ]
