# Generated by Django 3.1.7 on 2021-03-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intershala_admin', '0028_auto_20210314_1922'),
        ('job_profile', '0016_auto_20210314_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intershala_admin.intershalacompany'),
        ),
    ]
