# Generated by Django 3.1.7 on 2021-03-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210305_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_links',
        ),
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_name',
        ),
    ]
