# Generated by Django 3.1.7 on 2021-03-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0010_profile_state'),
        ('student', '0005_auto_20210305_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('applied_on', models.DateTimeField(auto_now=True)),
                ('resume', models.URLField(max_length=800)),
                ('status', models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('in_touch', 'in_touch'), ('Applied', 'Applied')], default='Applied', max_length=50)),
                ('other_links', models.URLField(blank=True, max_length=800, null=True)),
                ('answer', models.ManyToManyField(blank=True, null=True, to='job_profile.Assessment_answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profile.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
