# Generated by Django 3.1.7 on 2021-03-06 04:44

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
