# Generated by Django 3.1.7 on 2021-03-06 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210306_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 6, 4, 58, 47, 660585, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
