# Generated by Django 3.1.7 on 2021-03-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applied_application',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_application', to='student.StudentApplication'),
        ),
    ]
