# Generated by Django 3.1.7 on 2021-03-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='sonu', max_length=50),
            preserve_default=False,
        ),
    ]
