# Generated by Django 3.1.7 on 2021-03-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
