# Generated by Django 3.1.7 on 2021-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210314_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='get_notified',
            field=models.BooleanField(default=True),
        ),
    ]
